services:
  webContainer:
    container_name: notify
    image: aungzan/ubuntu-ssl
    ports:
      - '443:443'
    volumes:
      - '.:/var/www/html'
    depends_on:
      - dbContainer

  dbContainer:
    container_name: mysql
    image: mysql
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=P@ssw0rd
      - MYSQL_DATABASE=notify
      - MYSQL_USER=aungminzan
      - MYSQL_PASSWORD=password